# Generated by Django 5.0 on 2023-12-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('data', models.JSONField()),
                ('version', models.GeneratedField(db_persist=True, expression=models.F('data__info__version'), output_field=models.TextField())),
            ],
        ),
    ]
